name: client
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  flutter_native_splash: ^2.3.3
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/

  # fonts:
  #   - assets/fonts/

flutter_native_splash:
  color: "#42a5f5"
  color_dark: "#042a49"
  image: "assets/icons/splash.png"
  image_dark: "assets/icons/splash.png"

  android_12:
    color: "#42a5f5"
    image_dark: assets/icons/splash.png
    color_dark: "#042a49"

    icon_background_color_dark: "#eeeeee"
    icon_background_color: "#111111"

    branding: assets/icons/icon.png
